wandb_version: 1

alpha:
  value: 0.5100300447774669
batch_size:
  value: 16
learning_rate:
  value: 7.222074146859919e-05
max_depth:
  value: 20
min_samples_leaf:
  value: 1
min_samples_split:
  value: 10
model_type:
  value: RandomForest
n_estimators:
  value: 100
