wandb_version: 1

alpha:
  value: 0.34518474157833123
batch_size:
  value: 32
learning_rate:
  value: 0.0002906552602144037
max_depth:
  value: 10
min_samples_leaf:
  value: 4
min_samples_split:
  value: 2
model_type:
  value: RandomForest
n_estimators:
  value: 50
