wandb_version: 1

alpha:
  value: 0.8999088827721374
batch_size:
  value: 32
learning_rate:
  value: 0.0005034509795005899
max_depth:
  value: 5
min_samples_leaf:
  value: 1
min_samples_split:
  value: 5
model_type:
  value: GradientBoosting
n_estimators:
  value: 50
