wandb_version: 1

alpha:
  value: 0.22691725225344528
batch_size:
  value: 64
learning_rate:
  value: 0.004084679422451796
max_depth:
  value: 20
min_samples_leaf:
  value: 2
min_samples_split:
  value: 10
model_type:
  value: GradientBoosting
n_estimators:
  value: 100
