wandb_version: 1

alpha:
  value: 0.2947422854321613
batch_size:
  value: 32
learning_rate:
  value: 3.727799430025221e-05
max_depth:
  value: 10
min_samples_leaf:
  value: 2
min_samples_split:
  value: 10
model_type:
  value: RandomForest
n_estimators:
  value: 50
