wandb_version: 1

alpha:
  value: 0.6202564027875559
batch_size:
  value: 32
learning_rate:
  value: 6.798126481360712e-05
max_depth:
  value: 20
min_samples_leaf:
  value: 1
min_samples_split:
  value: 10
model_type:
  value: GradientBoosting
n_estimators:
  value: 50
