_wandb:
    value:
        cli_version: 0.23.1
        e:
            i8qzc4er4ykccyq3mfpi9uio3t8dbzu0:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                args:
                    - --alpha=0.2964504799059162
                    - --batch_size=16
                    - --learning_rate=1.673277943036054e-05
                codePath: src/modeling/train.py
                codePathLocal: src/modeling/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "236621549568"
                email: livshitz.leva@gmail.com
                executable: /opt/anaconda3/bin/python
                git:
                    commit: c55222bf9ac87d1322d73abb655d7b093cba9f75
                    remote: https://github.com/Levliv/mlops
                host: Levs-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/lev/Documents/ml_practices/wine_quality/src/modeling/train.py
                python: CPython 3.12.2
                root: /Users/lev/Documents/ml_practices/wine_quality
                startedAt: "2025-12-15T08:27:58.536934Z"
                writerId: i8qzc4er4ykccyq3mfpi9uio3t8dbzu0
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
                - 14
                - 15
                - 16
            "4": 3.12.2
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
alpha:
    value: 0.2964504799059162
batch_size:
    value: 16
learning_rate:
    value: 1.673277943036054e-05
max_depth:
    value: 5
min_samples_leaf:
    value: 2
min_samples_split:
    value: 5
model_type:
    value: RandomForest
n_estimators:
    value: 10
random_state:
    value: 42
test_size:
    value: 0.2
