version: '3.8'

services:
  wine-quality:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wine_quality_app
    ports:
      - "8888:8888"  # Jupyter
    volumes:
      - .:/app
      - /app/__pycache__
      - ./storage/local/dvc-storage:/app/storage/local/dvc-storage
    environment:
      - PYTHONUNBUFFERED=1
      - DVC_REMOTE_LOCAL_URL=/app/storage/local/dvc-storage
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser
