wandb_version: 1

alpha:
  value: 0.04586946571848405
batch_size:
  value: 16
learning_rate:
  value: 0.00028631711224858
max_depth:
  value: 20
min_samples_leaf:
  value: 1
min_samples_split:
  value: 2
model_type:
  value: RandomForest
n_estimators:
  value: 200
