wandb_version: 1

alpha:
  value: 0.5062539942076949
batch_size:
  value: 64
learning_rate:
  value: 0.003491178629663247
max_depth:
  value: 20
min_samples_leaf:
  value: 1
min_samples_split:
  value: 5
model_type:
  value: RandomForest
n_estimators:
  value: 100
