wandb_version: 1

alpha:
  value: 0.3460519789007127
batch_size:
  value: 32
learning_rate:
  value: 0.00011035361043095832
max_depth:
  value: 20
min_samples_leaf:
  value: 4
min_samples_split:
  value: 2
model_type:
  value: GradientBoosting
n_estimators:
  value: 200
