wandb_version: 1

alpha:
  value: 0.38990117300598
batch_size:
  value: 16
learning_rate:
  value: 0.0005567736671271028
max_depth:
  value: 20
min_samples_leaf:
  value: 2
min_samples_split:
  value: 2
model_type:
  value: GradientBoosting
n_estimators:
  value: 100
