wandb_version: 1

alpha:
  value: 0.9047596191887
batch_size:
  value: 64
learning_rate:
  value: 0.0014469356326885115
max_depth:
  value: 20
min_samples_leaf:
  value: 4
min_samples_split:
  value: 5
model_type:
  value: RandomForest
n_estimators:
  value: 200
