wandb_version: 1

alpha:
  value: 0.7480617728833301
batch_size:
  value: 64
learning_rate:
  value: 0.0004845079184233686
max_depth:
  value: 20
min_samples_leaf:
  value: 2
min_samples_split:
  value: 2
model_type:
  value: RandomForest
n_estimators:
  value: 200
