wandb_version: 1

alpha:
  value: 0.7401610057896096
batch_size:
  value: 64
learning_rate:
  value: 0.0002636833505362854
max_depth:
  value: 20
min_samples_leaf:
  value: 4
min_samples_split:
  value: 10
model_type:
  value: RandomForest
n_estimators:
  value: 100
