wandb_version: 1

alpha:
  value: 0.768331662600454
batch_size:
  value: 64
learning_rate:
  value: 0.002055620996496392
max_depth:
  value: 10
min_samples_leaf:
  value: 2
min_samples_split:
  value: 2
model_type:
  value: RandomForest
n_estimators:
  value: 50
