wandb_version: 1

alpha:
  value: 0.8315436238247781
batch_size:
  value: 64
learning_rate:
  value: 0.0012577758944389895
max_depth:
  value: 15
min_samples_leaf:
  value: 4
min_samples_split:
  value: 5
model_type:
  value: GradientBoosting
n_estimators:
  value: 100
