wandb_version: 1

alpha:
  value: 0.7283631607478054
batch_size:
  value: 32
learning_rate:
  value: 0.001977859012787517
max_depth:
  value: 20
min_samples_leaf:
  value: 2
min_samples_split:
  value: 5
model_type:
  value: RandomForest
n_estimators:
  value: 200
