_wandb:
    value:
        cli_version: 0.23.1
        e:
            hyztz40yt0eg5tnz0yw2uao4896y6btf:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                args:
                    - --alpha=0.038343356008534
                    - --batch_size=64
                    - --learning_rate=0.036106956391799255
                codePath: src/modeling/train.py
                codePathLocal: src/modeling/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "236598734848"
                email: livshitz.leva@gmail.com
                executable: /opt/anaconda3/bin/python
                git:
                    commit: c55222bf9ac87d1322d73abb655d7b093cba9f75
                    remote: https://github.com/Levliv/mlops
                host: Levs-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/lev/Documents/ml_practices/wine_quality/src/modeling/train.py
                python: CPython 3.12.2
                root: /Users/lev/Documents/ml_practices/wine_quality
                startedAt: "2025-12-15T08:28:21.020243Z"
                writerId: hyztz40yt0eg5tnz0yw2uao4896y6btf
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
                - 14
                - 15
                - 16
            "4": 3.12.2
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
alpha:
    value: 0.038343356008534
batch_size:
    value: 64
learning_rate:
    value: 0.036106956391799255
max_depth:
    value: 5
min_samples_leaf:
    value: 2
min_samples_split:
    value: 5
model_type:
    value: RandomForest
n_estimators:
    value: 10
random_state:
    value: 42
test_size:
    value: 0.2
