_wandb:
    value:
        cli_version: 0.23.1
        e:
            gimeo1nexx5rxh9b54aip1galckyl1ps:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "2147483648"
                codePath: src/modeling/train.py
                codePathLocal: src/modeling/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "177845178368"
                email: livshitz.leva@gmail.com
                executable: /Users/lev/Library/Caches/pypoetry/virtualenvs/src-Aew8q4CJ-py3.12/bin/python
                git:
                    commit: 9d38769a3135d8ed9ca00330a89a4528153e9a4e
                    remote: https://github.com/Levliv/mlops
                host: Levs-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/lev/Documents/ml_practices/wine_quality/src/modeling/train.py
                python: CPython 3.12.2
                root: /Users/lev/Documents/ml_practices/wine_quality
                startedAt: "2025-12-21T18:45:34.789509Z"
                writerId: gimeo1nexx5rxh9b54aip1galckyl1ps
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 5
                - 50
                - 53
                - 105
            "2":
                - 5
                - 50
                - 53
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.2
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
max_depth:
    value: 10
min_samples_leaf:
    value: 3
min_samples_split:
    value: 5
model_type:
    value: RandomForest
n_estimators:
    value: 40
random_state:
    value: 42
test_size:
    value: 0.2
