_wandb:
    value:
        cli_version: 0.23.1
        e:
            8d98bdzna9sl3pgqqi9yooot6u0f799z:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                codePath: src/modeling/train.py
                codePathLocal: src/modeling/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "163650244608"
                email: livshitz.leva@gmail.com
                executable: /Users/lev/Library/Caches/pypoetry/virtualenvs/src-Aew8q4CJ-py3.12/bin/python
                git:
                    commit: c4f83488a1c176df175984a526d059080626f941
                    remote: https://github.com/Levliv/mlops
                host: Levs-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/lev/Documents/ml_practices/wine_quality/src/modeling/train.py
                python: CPython 3.12.2
                root: /Users/lev/Documents/ml_practices/wine_quality
                startedAt: "2025-12-20T19:13:54.921006Z"
                writerId: 8d98bdzna9sl3pgqqi9yooot6u0f799z
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.2
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
max_depth:
    value: 5
min_samples_leaf:
    value: 2
min_samples_split:
    value: 5
model_type:
    value: RandomForest
n_estimators:
    value: 10
random_state:
    value: 42
test_size:
    value: 0.2
